### PR TITLE
1.3.0b1

### PR DESCRIPTION
**Pull request by SethMichaelLarson**
This is the ongoing work to support VirtualBox 5.2 beta via 1.3.0b1 #88

### CODE REVIEW

**Comment by SethMichaelLarson** [comment]
@mjdorma The `library.py` that I generated locally is different from the current one? Should I push it here or?

**Comment by SethMichaelLarson** [comment]
Nevermind it was just some artifacts of compiling with the Python 3.x version! Those are fixed in the latest commit. Now the two versions of `library.py` are identical regardless of what Python version is used to generate them :tada:

**Comment by SethMichaelLarson** [comment]
Whenever you're ready we can probably merge this and release to PyPI as 1.3.0b1 :)

**Comment by mjdorma** [comment]
Looks fantastic.

**Pull request merged**
